### ISSUE TITLE
[BUG] pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package

### ISSUE THREAD

**Issue by ooker777** [obsei/obsei#310]
I install `obsei[all]` in a venv, then run `python .\example\facebook_example.py`. I get:

```
10/24/2023 17:18:31 - WARNING - obsei - 

By default `pip install obsei` will only install core dependencies.
To install all required dependencies use `pip install obsei[all]`.
Refer https://obsei.com/#install-obsei for more options.

Traceback (most recent call last):
  File "D:\Programming\Topic modelling\obsei\example\facebook_example.py", line 4, in <module>
    from obsei.source.facebook_source import FacebookSource, FacebookSourceConfig
  File "D:\Programming\Topic modelling\obsei\.venv\Lib\site-packages\obsei\source\facebook_source.py", line 5, in <module>
    from pydantic import BaseSettings, Field, PrivateAttr
  File "D:\Programming\Topic modelling\obsei\.venv\Lib\site-packages\pydantic\__init__.py", line 218, in __getattr__    
    return _getattr_migration(attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\Topic modelling\obsei\.venv\Lib\site-packages\pydantic\_migration.py", line 294, in wrapper      
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.4/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.4/u/import-error  
```

I then `pip install pydantic-settings` and change line 5 of both [`obsei\source\facebook_source.py`](https://github.com/obsei/obsei/blob/6a942c21df05d9c153aff0228fc396d117591157/obsei/source/facebook_source.py#L5) and `.venv\Lib\site-packages\obsei\source\facebook_source.py` from 

```python
from pydantic import BaseSettings, Field, PrivateAttr
```
to 

```python
from pydantic import Field, PrivateAttr
from pydantic_settings import BaseSettings
```
and run again. I still get the same error. I don't know what goes wrong or the version of pydantic I need to use.

See also: [No module named 'pydantic.v1' even though pip list see it](https://stackoverflow.com/q/77351504/3416774)

**Comment by lalitpagaria** [comment]
@ooker777  Thanks for raising this issue. Can you please check with latest release 0.0.15 and confirm. We have moved to Pydantic V2
